### ISSUE TITLE
response.recordsFiltered has incorrect value if resulting item count is bigger than page size

### ISSUE THREAD

**Issue by djesionek** [darrachequesne/spring-data-mongodb-datatables#6] opened 2020-04-16 14:52 UTC
_DataTablesRepositoryImpl.findAll()_ queries the mongodb with the length limit from _DataTablesInput.length_, the length of the result for this query is set for _DataTablesOutput.recordsFiltered_. 
This way the resulting value of _DataTablesOutput.recordsFiltered_ equals the intended page length as max (or less if the result count is < page length) instead of "the total number of records after filtering has been applied" as defined in most current version of [DataTables SSP manual](https://datatables.net/manual/server-side).

This results in DataTables always rendering only one page, even if more results should be shown for a current filter.

Can you reproduce this behavior on a simple demo implementation of yours?
Unfortunately I wasn't able yet to setup a dev environment for this project to be able to test this properly.

**Comment by darrachequesne** [comment] 2020-04-28 05:52
Hi @djesionek, I was not able to reproduce the issue, could you please check https://github.com/darrachequesne/spring-data-mongodb-datatables-sample?

**Comment by djesionek** [comment] 2020-04-28 06:33
I will have a check, maybe there was something else wrong for some reason.

**Comment by djesionek** [comment] 2020-04-28 07:13
I can reproduce this by updating to 2.2.6.RELEASE of spring boot. I tested following versions of spring boot: 2.2.6.RELEASE, 2.2.5.RELEASE, 2.2.0.RELEASE (All non weorking), 2.1.0.RELEASE, 2.1.13.RELEASE (All working).

Looks like something changed from 2.2.0. Can you reproduce that as well?

**Comment by darrachequesne** [comment] 2020-04-28 07:28
@djesionek arf, you're right, I'm actually able to reproduce with `2.2.6.RELEASE`:

![image](https://user-images.githubusercontent.com/13031701/80459357-8f135380-8932-11ea-939a-aac9503ac17e.png)

**Comment by djesionek** [comment] 2020-04-28 09:01
So then it would be also good to check whether the fix breaks anything in older versions. If not then thats one pro to merge the PR.

**Comment by darrachequesne** [comment] 2020-04-29 05:44
Closed by https://github.com/darrachequesne/spring-data-mongodb-datatables/commit/8012b408b637f75a9540da4e8dc43c1dc3d16e37. The `1.0.3` release should show up in Maven central in a few hours.

**Closed as completed by darrachequesne** 2020-04-29 05:44 UTC
